apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: phxitz2fst2p01.corp.nutanix.com
    path: "/awx-projects"
    readOnly: false
